services:
  test_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
