version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  client:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - server
    env_file:
      - ./client/.env
  server:
    build: ./server
    ports:
      - '3001:3001'
    depends_on:
      - db
    env_file:
      - ./server/.env
    volumes:
      - ./server/prisma:/app/prisma
      - ./server/node_modules:/app/node_modules
volumes:
  db_data:
