services:
  test_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  db_data:

# separate network to prevent conflict with development
networks:
  test_network:
    driver: bridge
